#!/usr/bin/env bash
# generate-architecture.sh — Query GitNexus knowledge graph and generate ARCHITECTURE.md
# Usage: bash .github/scripts/generate-architecture.sh
# Requires: npx (with gitnexus), jq, git
# Output: Writes ARCHITECTURE.md to the current directory
set -euo pipefail

# ── Dependency validation ─────────────────────────────────────────────
check_deps() {
  local missing=()
  for cmd in jq npx; do
    if ! command -v "$cmd" &>/dev/null; then
      missing+=("$cmd")
    fi
  done
  if [[ ${#missing[@]} -gt 0 ]]; then
    echo "::error::Missing required dependencies: ${missing[*]}" >&2
    exit 1
  fi
}

check_deps

# ── Query GitNexus for architectural data ─────────────────────────────
query_gitnexus() {
  local query="$1"
  local result
  if ! result=$(npx gitnexus query "$query" --limit 10 2>&1); then
    echo "::warning::GitNexus query failed for '$query': $result" >&2
    echo '{"processes":[]}'
    return
  fi
  # Validate we got valid JSON
  if ! echo "$result" | jq -e '.processes' >/dev/null 2>&1; then
    echo "::warning::GitNexus returned invalid JSON for '$query'" >&2
    echo '{"processes":[]}'
    return
  fi
  echo "$result"
}

echo "Querying GitNexus knowledge graph..." >&2

ENTRY_POINTS=$(query_gitnexus "entry points main CLI")
CORE_MODULES=$(query_gitnexus "core modules services")
DATA_FLOW=$(query_gitnexus "data flow pipeline")
AGENTS=$(query_gitnexus "agent orchestration")

# ── Extract process summaries ─────────────────────────────────────────
extract_summaries() {
  echo "$1" | jq -r '[.processes[]? | .summary] | join("\n")' 2>/dev/null || echo "none"
}

ENTRY_SUMMARY=$(extract_summaries "$ENTRY_POINTS")
CORE_SUMMARY=$(extract_summaries "$CORE_MODULES")
DATA_SUMMARY=$(extract_summaries "$DATA_FLOW")
AGENT_SUMMARY=$(extract_summaries "$AGENTS")

# ── Count files by extension ──────────────────────────────────────────
PY_COUNT=$(find . -name '*.py' -not -path './.git/*' -not -path './.gitnexus/*' | wc -l)
RS_COUNT=$(find . -name '*.rs' -not -path './.git/*' -not -path './.gitnexus/*' | wc -l)
YML_COUNT=$(find . -name '*.yml' -path './.github/*' | wc -l)
MD_COUNT=$(find . -name '*.md' -not -path './.git/*' -not -path './.gitnexus/*' | wc -l)

# ── Helper: render section ────────────────────────────────────────────
render_section() {
  local title="$1"
  local summary="$2"
  local fallback="$3"

  echo "## $title"
  echo ""
  if [[ -n "$summary" && "$summary" != "none" ]]; then
    echo "$summary" | while IFS= read -r line; do
      [[ -n "$line" ]] && echo "- $line"
    done
  else
    echo "- $fallback"
  fi
  echo ""
}

# ── Generate ARCHITECTURE.md ──────────────────────────────────────────
GENERATED_DATE=$(date -u '+%Y-%m-%d %H:%M UTC')

cat > ARCHITECTURE.md <<EOF
# SuperClaude Architecture

> Auto-generated by GitNexus knowledge graph analysis.
> Last updated: ${GENERATED_DATE}

## Codebase Overview

| Metric | Count |
|--------|-------|
| Python files | ${PY_COUNT} |
| Rust files | ${RS_COUNT} |
| GitHub workflows | ${YML_COUNT} |
| Documentation files | ${MD_COUNT} |

EOF

{
  render_section "Entry Points" "$ENTRY_SUMMARY" "No entry points detected"
  render_section "Core Modules" "$CORE_SUMMARY" "No core modules detected"
  render_section "Data Flow" "$DATA_SUMMARY" "No data flows detected"
  render_section "Agent Orchestration" "$AGENT_SUMMARY" "No agent orchestration detected"
  echo "---"
  echo "*Generated by [GitNexus](https://github.com/nicholasgriffintn/gitnexus) code intelligence*"
} >> ARCHITECTURE.md

# ── Validate output ───────────────────────────────────────────────────
if [[ ! -s ARCHITECTURE.md ]]; then
  echo "::error::Generated ARCHITECTURE.md is empty" >&2
  exit 1
fi

if ! head -1 ARCHITECTURE.md | grep -q '^# '; then
  echo "::error::Generated ARCHITECTURE.md does not start with a heading" >&2
  exit 1
fi

for section in "Codebase Overview" "Entry Points" "Core Modules"; do
  if ! grep -q "## $section" ARCHITECTURE.md; then
    echo "::error::Generated ARCHITECTURE.md missing expected section: $section" >&2
    exit 1
  fi
done

echo "ARCHITECTURE.md generated successfully ($(wc -l < ARCHITECTURE.md) lines)" >&2
