#!/usr/bin/env bash
# gitnexus-report.sh — Bridge git diff → GitNexus impact → markdown report
# Usage: bash .github/scripts/gitnexus-report.sh <base_ref>
# Output: REPORT.md written to stdout, risk level to $GITHUB_OUTPUT (if available)
set -euo pipefail

BASE_REF="${1:?Usage: gitnexus-report.sh <base_ref>}"
MAX_DEPTH="${GITNEXUS_DEPTH:-3}"
MAX_FILES="${GITNEXUS_MAX_FILES:-50}"

# ── Collect changed files ─────────────────────────────────────────────
mapfile -t CHANGED_FILES < <(git diff --name-only "origin/${BASE_REF}...HEAD" -- '*.py' '*.rs' '*.js' '*.ts' '*.tsx' '*.jsx' '*.yml' '*.yaml' 2>/dev/null || true)

if [[ ${#CHANGED_FILES[@]} -eq 0 ]]; then
  echo "No code files changed — skipping impact analysis."
  if [[ -n "${GITHUB_OUTPUT:-}" ]]; then
    echo "risk=NONE" >> "$GITHUB_OUTPUT"
    echo "report=No code files changed." >> "$GITHUB_OUTPUT"
  fi
  exit 0
fi

echo "Analyzing ${#CHANGED_FILES[@]} changed files..." >&2

# ── Cap file count to avoid excessive CI time ─────────────────────────
if [[ ${#CHANGED_FILES[@]} -gt $MAX_FILES ]]; then
  echo "Warning: ${#CHANGED_FILES[@]} files changed, capping analysis to $MAX_FILES" >&2
  CHANGED_FILES=("${CHANGED_FILES[@]:0:$MAX_FILES}")
fi

# ── Run impact analysis per file ──────────────────────────────────────
declare -A FILE_RISKS
OVERALL_RISK="LOW"
TOTAL_IMPACTED=0
ALL_PROCESSES=()
ALL_MODULES=()
IMPACT_DETAILS=()

risk_rank() {
  case "$1" in
    CRITICAL) echo 4 ;;
    HIGH)     echo 3 ;;
    MEDIUM)   echo 2 ;;
    LOW)      echo 1 ;;
    *)        echo 0 ;;
  esac
}

risk_badge() {
  case "$1" in
    CRITICAL) echo ":red_circle: **CRITICAL**" ;;
    HIGH)     echo ":orange_circle: **HIGH**" ;;
    MEDIUM)   echo ":yellow_circle: **MEDIUM**" ;;
    LOW)      echo ":green_circle: **LOW**" ;;
    *)        echo ":white_circle: **NONE**" ;;
  esac
}

for file in "${CHANGED_FILES[@]}"; do
  # Try file-level impact first
  result=$(npx gitnexus impact "$file" --direction upstream --depth "$MAX_DEPTH" 2>/dev/null || echo '{"error":"not found"}')

  if echo "$result" | jq -e '.error' >/dev/null 2>&1; then
    FILE_RISKS["$file"]="UNKNOWN"
    continue
  fi

  file_risk=$(echo "$result" | jq -r '.risk // "LOW"')
  impacted=$(echo "$result" | jq -r '.impactedCount // 0')
  FILE_RISKS["$file"]="$file_risk"
  TOTAL_IMPACTED=$((TOTAL_IMPACTED + impacted))

  # Collect affected processes
  procs=$(echo "$result" | jq -r '.affected_processes[]?.name // empty' 2>/dev/null || true)
  while IFS= read -r p; do
    [[ -n "$p" ]] && ALL_PROCESSES+=("$p")
  done <<< "$procs"

  # Collect affected modules
  mods=$(echo "$result" | jq -r '.affected_modules[]?.name // empty' 2>/dev/null || true)
  while IFS= read -r m; do
    [[ -n "$m" ]] && ALL_MODULES+=("$m")
  done <<< "$mods"

  # Collect depth details for report
  depth_summary=$(echo "$result" | jq -r '
    [.byDepth | to_entries[] | .value[] |
      {depth: .depth, name: .name, filePath: .filePath, relationType: .relationType}
    ] | group_by(.depth) | map({
      depth: .[0].depth,
      count: length,
      symbols: [.[:3][] | .name] | join(", ")
    }) | .[] | "Depth \(.depth): \(.count) symbols (\(.symbols))"
  ' 2>/dev/null || echo "  No downstream impacts")
  IMPACT_DETAILS+=("### \`$file\` — $(risk_badge "$file_risk")")
  IMPACT_DETAILS+=("$depth_summary")
  IMPACT_DETAILS+=("")

  # Update overall risk
  if [[ $(risk_rank "$file_risk") -gt $(risk_rank "$OVERALL_RISK") ]]; then
    OVERALL_RISK="$file_risk"
  fi
done

# ── Deduplicate processes and modules ─────────────────────────────────
UNIQUE_PROCESSES=($(printf '%s\n' "${ALL_PROCESSES[@]}" 2>/dev/null | sort -u || true))
UNIQUE_MODULES=($(printf '%s\n' "${ALL_MODULES[@]}" 2>/dev/null | sort -u || true))

# ── Generate markdown report ──────────────────────────────────────────
cat <<REPORT
<!-- gitnexus-impact -->
## GitNexus Impact Analysis

$(risk_badge "$OVERALL_RISK") Overall Risk Level

| Metric | Value |
|--------|-------|
| Files Analyzed | ${#CHANGED_FILES[@]} |
| Total Impacted Symbols | $TOTAL_IMPACTED |
| Affected Processes | ${#UNIQUE_PROCESSES[@]} |
| Affected Modules | ${#UNIQUE_MODULES[@]} |

### Per-File Impact

| File | Risk |
|------|------|
$(for file in "${CHANGED_FILES[@]}"; do
  r="${FILE_RISKS[$file]:-UNKNOWN}"
  echo "| \`$file\` | $(risk_badge "$r") |"
done)

$(if [[ ${#UNIQUE_PROCESSES[@]} -gt 0 ]]; then
  echo "### Affected Processes"
  for p in "${UNIQUE_PROCESSES[@]}"; do echo "- $p"; done
fi)

$(if [[ ${#UNIQUE_MODULES[@]} -gt 0 ]]; then
  echo "### Affected Modules"
  for m in "${UNIQUE_MODULES[@]}"; do echo "- $m"; done
fi)

<details>
<summary>Detailed Impact by File</summary>

$(printf '%s\n' "${IMPACT_DETAILS[@]}")

</details>

---
*Generated by [GitNexus](https://github.com/nicholasgriffintn/gitnexus) impact analysis*
REPORT

# ── Output for GitHub Actions ─────────────────────────────────────────
if [[ -n "${GITHUB_OUTPUT:-}" ]]; then
  echo "risk=$OVERALL_RISK" >> "$GITHUB_OUTPUT"
fi

echo "Overall risk: $OVERALL_RISK" >&2
