// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AgentEvent {
    #[prost(string, tag = "1")]
    pub execution_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(
        oneof = "agent_event::Event",
        tags = "10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21"
    )]
    pub event: ::core::option::Option<agent_event::Event>,
}
/// Nested message and enum types in `AgentEvent`.
pub mod agent_event {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Event {
        #[prost(message, tag = "10")]
        IterationStarted(super::IterationStarted),
        #[prost(message, tag = "11")]
        IterationCompleted(super::IterationCompleted),
        #[prost(message, tag = "12")]
        ToolInvoked(super::ToolInvoked),
        #[prost(message, tag = "13")]
        FileChanged(super::FileChanged),
        #[prost(message, tag = "14")]
        TestResult(super::TestResult),
        #[prost(message, tag = "15")]
        ScoreUpdated(super::ScoreUpdated),
        #[prost(message, tag = "16")]
        StateChanged(super::StateChanged),
        #[prost(message, tag = "17")]
        SubagentSpawned(super::SubagentSpawned),
        #[prost(message, tag = "18")]
        SubagentCompleted(super::SubagentCompleted),
        #[prost(message, tag = "19")]
        ArtifactWritten(super::ArtifactWritten),
        #[prost(message, tag = "20")]
        LogMessage(super::LogMessage),
        #[prost(message, tag = "21")]
        Error(super::ErrorOccurred),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IterationStarted {
    #[prost(int32, tag = "1")]
    pub iteration: i32,
    /// Tree depth for visualization
    #[prost(int32, tag = "2")]
    pub depth: i32,
    /// Unique ID for tree node
    #[prost(string, tag = "3")]
    pub node_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IterationCompleted {
    #[prost(int32, tag = "1")]
    pub iteration: i32,
    #[prost(float, tag = "2")]
    pub score: f32,
    #[prost(string, repeated, tag = "3")]
    pub improvements: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "4")]
    pub dimensions: ::core::option::Option<QualityDimensions>,
    #[prost(float, tag = "5")]
    pub duration_seconds: f32,
    #[prost(string, tag = "6")]
    pub node_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ToolInvoked {
    #[prost(string, tag = "1")]
    pub tool_name: ::prost::alloc::string::String,
    /// Brief description, not full output
    #[prost(string, tag = "2")]
    pub summary: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub blocked: bool,
    #[prost(string, tag = "4")]
    pub block_reason: ::prost::alloc::string::String,
    #[prost(int32, tag = "5")]
    pub depth: i32,
    #[prost(string, tag = "6")]
    pub node_id: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub parent_node_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileChanged {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(enumeration = "FileAction", tag = "2")]
    pub action: i32,
    #[prost(int32, tag = "3")]
    pub lines_added: i32,
    #[prost(int32, tag = "4")]
    pub lines_removed: i32,
    #[prost(string, tag = "5")]
    pub node_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TestResult {
    #[prost(string, tag = "1")]
    pub framework: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub passed: i32,
    #[prost(int32, tag = "3")]
    pub failed: i32,
    #[prost(int32, tag = "4")]
    pub skipped: i32,
    #[prost(float, tag = "5")]
    pub coverage_percent: f32,
    #[prost(string, repeated, tag = "6")]
    pub failed_tests: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "7")]
    pub node_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ScoreUpdated {
    #[prost(float, tag = "1")]
    pub old_score: f32,
    #[prost(float, tag = "2")]
    pub new_score: f32,
    #[prost(string, tag = "3")]
    pub reason: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub dimensions: ::core::option::Option<QualityDimensions>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StateChanged {
    #[prost(enumeration = "ExecutionState", tag = "1")]
    pub old_state: i32,
    #[prost(enumeration = "ExecutionState", tag = "2")]
    pub new_state: i32,
    #[prost(string, tag = "3")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubagentSpawned {
    #[prost(string, tag = "1")]
    pub subagent_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub subagent_type: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub task_summary: ::prost::alloc::string::String,
    #[prost(int32, tag = "4")]
    pub depth: i32,
    #[prost(string, tag = "5")]
    pub node_id: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub parent_node_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubagentCompleted {
    #[prost(string, tag = "1")]
    pub subagent_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub success: bool,
    #[prost(string, tag = "3")]
    pub result_summary: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub node_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ArtifactWritten {
    /// Relative path in vault
    #[prost(string, tag = "1")]
    pub obsidian_path: ::prost::alloc::string::String,
    /// "decision", "evidence", "summary"
    #[prost(string, tag = "2")]
    pub artifact_type: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub title: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogMessage {
    #[prost(enumeration = "LogLevel", tag = "1")]
    pub level: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub source: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ErrorOccurred {
    #[prost(string, tag = "1")]
    pub error_type: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub traceback: ::prost::alloc::string::String,
    #[prost(bool, tag = "4")]
    pub recoverable: bool,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct QualityDimensions {
    #[prost(float, tag = "1")]
    pub code_changes: f32,
    #[prost(float, tag = "2")]
    pub tests_run: f32,
    #[prost(float, tag = "3")]
    pub tests_pass: f32,
    #[prost(float, tag = "4")]
    pub coverage: f32,
    #[prost(float, tag = "5")]
    pub no_errors: f32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StartExecutionRequest {
    #[prost(string, tag = "1")]
    pub task: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub project_root: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub config: ::core::option::Option<ExecutionConfig>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StartExecutionResponse {
    #[prost(string, tag = "1")]
    pub execution_id: ::prost::alloc::string::String,
    #[prost(enumeration = "ExecutionState", tag = "2")]
    pub state: i32,
    #[prost(message, optional, tag = "3")]
    pub started_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StopExecutionRequest {
    #[prost(string, tag = "1")]
    pub execution_id: ::prost::alloc::string::String,
    /// Force immediate termination
    #[prost(bool, tag = "2")]
    pub force: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StopExecutionResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PauseExecutionRequest {
    #[prost(string, tag = "1")]
    pub execution_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PauseExecutionResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ResumeExecutionRequest {
    #[prost(string, tag = "1")]
    pub execution_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ResumeExecutionResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecutionConfig {
    #[prost(int32, tag = "1")]
    pub max_iterations: i32,
    #[prost(float, tag = "2")]
    pub quality_threshold: f32,
    /// "sonnet", "opus", "haiku"
    #[prost(string, tag = "3")]
    pub model: ::prost::alloc::string::String,
    #[prost(float, tag = "4")]
    pub timeout_seconds: f32,
    #[prost(bool, tag = "5")]
    pub pal_review_enabled: bool,
    #[prost(float, tag = "6")]
    pub min_improvement: f32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetConfigurationRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetConfigurationResponse {
    #[prost(message, optional, tag = "1")]
    pub default_config: ::core::option::Option<ExecutionConfig>,
    #[prost(message, optional, tag = "2")]
    pub obsidian_config: ::core::option::Option<ObsidianConfig>,
    #[prost(string, repeated, tag = "3")]
    pub available_models: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateConfigurationRequest {
    #[prost(message, optional, tag = "1")]
    pub config: ::core::option::Option<ExecutionConfig>,
    #[prost(message, optional, tag = "2")]
    pub obsidian_config: ::core::option::Option<ObsidianConfig>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateConfigurationResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetStatusRequest {
    #[prost(string, tag = "1")]
    pub execution_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetStatusResponse {
    #[prost(message, optional, tag = "1")]
    pub status: ::core::option::Option<ExecutionStatus>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ListExecutionsRequest {
    #[prost(bool, tag = "1")]
    pub include_completed: bool,
    #[prost(int32, tag = "2")]
    pub limit: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListExecutionsResponse {
    #[prost(message, repeated, tag = "1")]
    pub executions: ::prost::alloc::vec::Vec<ExecutionSummary>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecutionSummary {
    #[prost(string, tag = "1")]
    pub execution_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub task: ::prost::alloc::string::String,
    #[prost(enumeration = "ExecutionState", tag = "3")]
    pub state: i32,
    #[prost(int32, tag = "4")]
    pub current_iteration: i32,
    #[prost(float, tag = "5")]
    pub current_score: f32,
    #[prost(message, optional, tag = "6")]
    pub started_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecutionStatus {
    #[prost(string, tag = "1")]
    pub execution_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub task: ::prost::alloc::string::String,
    #[prost(enumeration = "ExecutionState", tag = "3")]
    pub state: i32,
    #[prost(int32, tag = "4")]
    pub current_iteration: i32,
    #[prost(int32, tag = "5")]
    pub max_iterations: i32,
    #[prost(float, tag = "6")]
    pub current_score: f32,
    #[prost(float, tag = "7")]
    pub quality_threshold: f32,
    #[prost(string, tag = "8")]
    pub termination_reason: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "9")]
    pub evidence: ::core::option::Option<EvidenceSummary>,
    #[prost(message, optional, tag = "10")]
    pub started_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "11")]
    pub ended_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EvidenceSummary {
    #[prost(string, repeated, tag = "1")]
    pub files_written: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "2")]
    pub files_edited: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(int32, tag = "3")]
    pub commands_run: i32,
    #[prost(bool, tag = "4")]
    pub tests_run: bool,
    #[prost(int32, tag = "5")]
    pub tests_passed: i32,
    #[prost(int32, tag = "6")]
    pub tests_failed: i32,
    #[prost(int32, tag = "7")]
    pub subagents_spawned: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamEventsRequest {
    #[prost(string, tag = "1")]
    pub execution_id: ::prost::alloc::string::String,
    /// Send past events first
    #[prost(bool, tag = "2")]
    pub include_history: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ObsidianConfig {
    #[prost(string, tag = "1")]
    pub vault_path: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub read_paths: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "3")]
    pub output_base: ::prost::alloc::string::String,
    /// "task_completion", "manual", "never"
    #[prost(string, tag = "4")]
    pub sync_on: ::prost::alloc::string::String,
    #[prost(bool, tag = "5")]
    pub backlinks_enabled: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListObsidianNotesRequest {
    #[prost(string, tag = "1")]
    pub project_filter: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub tag_filter: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub limit: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListObsidianNotesResponse {
    #[prost(message, repeated, tag = "1")]
    pub notes: ::prost::alloc::vec::Vec<ObsidianNoteSummary>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ObsidianNoteSummary {
    #[prost(string, tag = "1")]
    pub relative_path: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "4")]
    pub summary: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub project: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "6")]
    pub modified_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetObsidianNoteRequest {
    #[prost(string, tag = "1")]
    pub relative_path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetObsidianNoteResponse {
    #[prost(string, tag = "1")]
    pub relative_path: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub content: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "4")]
    pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "5")]
    pub project: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PingRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PingResponse {
    #[prost(string, tag = "1")]
    pub version: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub active_executions: i32,
    #[prost(message, optional, tag = "3")]
    pub uptime_since: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum FileAction {
    Unspecified = 0,
    Read = 1,
    Write = 2,
    Edit = 3,
    Delete = 4,
}
impl FileAction {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "FILE_ACTION_UNSPECIFIED",
            Self::Read => "FILE_ACTION_READ",
            Self::Write => "FILE_ACTION_WRITE",
            Self::Edit => "FILE_ACTION_EDIT",
            Self::Delete => "FILE_ACTION_DELETE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "FILE_ACTION_UNSPECIFIED" => Some(Self::Unspecified),
            "FILE_ACTION_READ" => Some(Self::Read),
            "FILE_ACTION_WRITE" => Some(Self::Write),
            "FILE_ACTION_EDIT" => Some(Self::Edit),
            "FILE_ACTION_DELETE" => Some(Self::Delete),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum LogLevel {
    Unspecified = 0,
    Debug = 1,
    Info = 2,
    Warn = 3,
    Error = 4,
}
impl LogLevel {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "LOG_LEVEL_UNSPECIFIED",
            Self::Debug => "LOG_LEVEL_DEBUG",
            Self::Info => "LOG_LEVEL_INFO",
            Self::Warn => "LOG_LEVEL_WARN",
            Self::Error => "LOG_LEVEL_ERROR",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "LOG_LEVEL_UNSPECIFIED" => Some(Self::Unspecified),
            "LOG_LEVEL_DEBUG" => Some(Self::Debug),
            "LOG_LEVEL_INFO" => Some(Self::Info),
            "LOG_LEVEL_WARN" => Some(Self::Warn),
            "LOG_LEVEL_ERROR" => Some(Self::Error),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ExecutionState {
    Unspecified = 0,
    Pending = 1,
    Running = 2,
    Paused = 3,
    Completed = 4,
    Failed = 5,
    Cancelled = 6,
}
impl ExecutionState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "EXECUTION_STATE_UNSPECIFIED",
            Self::Pending => "EXECUTION_STATE_PENDING",
            Self::Running => "EXECUTION_STATE_RUNNING",
            Self::Paused => "EXECUTION_STATE_PAUSED",
            Self::Completed => "EXECUTION_STATE_COMPLETED",
            Self::Failed => "EXECUTION_STATE_FAILED",
            Self::Cancelled => "EXECUTION_STATE_CANCELLED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "EXECUTION_STATE_UNSPECIFIED" => Some(Self::Unspecified),
            "EXECUTION_STATE_PENDING" => Some(Self::Pending),
            "EXECUTION_STATE_RUNNING" => Some(Self::Running),
            "EXECUTION_STATE_PAUSED" => Some(Self::Paused),
            "EXECUTION_STATE_COMPLETED" => Some(Self::Completed),
            "EXECUTION_STATE_FAILED" => Some(Self::Failed),
            "EXECUTION_STATE_CANCELLED" => Some(Self::Cancelled),
            _ => None,
        }
    }
}
/// Generated server implementations.
pub mod super_claude_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with SuperClaudeServiceServer.
    #[async_trait]
    pub trait SuperClaudeService: std::marker::Send + std::marker::Sync + 'static {
        /// Execution lifecycle
        async fn start_execution(
            &self,
            request: tonic::Request<super::StartExecutionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::StartExecutionResponse>,
            tonic::Status,
        >;
        async fn stop_execution(
            &self,
            request: tonic::Request<super::StopExecutionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::StopExecutionResponse>,
            tonic::Status,
        >;
        async fn pause_execution(
            &self,
            request: tonic::Request<super::PauseExecutionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::PauseExecutionResponse>,
            tonic::Status,
        >;
        async fn resume_execution(
            &self,
            request: tonic::Request<super::ResumeExecutionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ResumeExecutionResponse>,
            tonic::Status,
        >;
        /// Monitoring
        async fn get_status(
            &self,
            request: tonic::Request<super::GetStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetStatusResponse>,
            tonic::Status,
        >;
        async fn list_executions(
            &self,
            request: tonic::Request<super::ListExecutionsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListExecutionsResponse>,
            tonic::Status,
        >;
        /// Server streaming response type for the StreamEvents method.
        type StreamEventsStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::AgentEvent, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        async fn stream_events(
            &self,
            request: tonic::Request<super::StreamEventsRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::StreamEventsStream>,
            tonic::Status,
        >;
        /// Configuration
        async fn get_configuration(
            &self,
            request: tonic::Request<super::GetConfigurationRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetConfigurationResponse>,
            tonic::Status,
        >;
        async fn update_configuration(
            &self,
            request: tonic::Request<super::UpdateConfigurationRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UpdateConfigurationResponse>,
            tonic::Status,
        >;
        /// Obsidian integration (metadata only - files on disk)
        async fn list_obsidian_notes(
            &self,
            request: tonic::Request<super::ListObsidianNotesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListObsidianNotesResponse>,
            tonic::Status,
        >;
        async fn get_obsidian_note(
            &self,
            request: tonic::Request<super::GetObsidianNoteRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetObsidianNoteResponse>,
            tonic::Status,
        >;
        /// Health check
        async fn ping(
            &self,
            request: tonic::Request<super::PingRequest>,
        ) -> std::result::Result<tonic::Response<super::PingResponse>, tonic::Status>;
    }
    /// Main SuperClaude orchestration service
    #[derive(Debug)]
    pub struct SuperClaudeServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> SuperClaudeServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for SuperClaudeServiceServer<T>
    where
        T: SuperClaudeService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/superclaude.v1.SuperClaudeService/StartExecution" => {
                    #[allow(non_camel_case_types)]
                    struct StartExecutionSvc<T: SuperClaudeService>(pub Arc<T>);
                    impl<
                        T: SuperClaudeService,
                    > tonic::server::UnaryService<super::StartExecutionRequest>
                    for StartExecutionSvc<T> {
                        type Response = super::StartExecutionResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::StartExecutionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SuperClaudeService>::start_execution(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StartExecutionSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/superclaude.v1.SuperClaudeService/StopExecution" => {
                    #[allow(non_camel_case_types)]
                    struct StopExecutionSvc<T: SuperClaudeService>(pub Arc<T>);
                    impl<
                        T: SuperClaudeService,
                    > tonic::server::UnaryService<super::StopExecutionRequest>
                    for StopExecutionSvc<T> {
                        type Response = super::StopExecutionResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::StopExecutionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SuperClaudeService>::stop_execution(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StopExecutionSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/superclaude.v1.SuperClaudeService/PauseExecution" => {
                    #[allow(non_camel_case_types)]
                    struct PauseExecutionSvc<T: SuperClaudeService>(pub Arc<T>);
                    impl<
                        T: SuperClaudeService,
                    > tonic::server::UnaryService<super::PauseExecutionRequest>
                    for PauseExecutionSvc<T> {
                        type Response = super::PauseExecutionResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PauseExecutionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SuperClaudeService>::pause_execution(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = PauseExecutionSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/superclaude.v1.SuperClaudeService/ResumeExecution" => {
                    #[allow(non_camel_case_types)]
                    struct ResumeExecutionSvc<T: SuperClaudeService>(pub Arc<T>);
                    impl<
                        T: SuperClaudeService,
                    > tonic::server::UnaryService<super::ResumeExecutionRequest>
                    for ResumeExecutionSvc<T> {
                        type Response = super::ResumeExecutionResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ResumeExecutionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SuperClaudeService>::resume_execution(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ResumeExecutionSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/superclaude.v1.SuperClaudeService/GetStatus" => {
                    #[allow(non_camel_case_types)]
                    struct GetStatusSvc<T: SuperClaudeService>(pub Arc<T>);
                    impl<
                        T: SuperClaudeService,
                    > tonic::server::UnaryService<super::GetStatusRequest>
                    for GetStatusSvc<T> {
                        type Response = super::GetStatusResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetStatusRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SuperClaudeService>::get_status(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetStatusSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/superclaude.v1.SuperClaudeService/ListExecutions" => {
                    #[allow(non_camel_case_types)]
                    struct ListExecutionsSvc<T: SuperClaudeService>(pub Arc<T>);
                    impl<
                        T: SuperClaudeService,
                    > tonic::server::UnaryService<super::ListExecutionsRequest>
                    for ListExecutionsSvc<T> {
                        type Response = super::ListExecutionsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListExecutionsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SuperClaudeService>::list_executions(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListExecutionsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/superclaude.v1.SuperClaudeService/StreamEvents" => {
                    #[allow(non_camel_case_types)]
                    struct StreamEventsSvc<T: SuperClaudeService>(pub Arc<T>);
                    impl<
                        T: SuperClaudeService,
                    > tonic::server::ServerStreamingService<super::StreamEventsRequest>
                    for StreamEventsSvc<T> {
                        type Response = super::AgentEvent;
                        type ResponseStream = T::StreamEventsStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::StreamEventsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SuperClaudeService>::stream_events(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StreamEventsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/superclaude.v1.SuperClaudeService/GetConfiguration" => {
                    #[allow(non_camel_case_types)]
                    struct GetConfigurationSvc<T: SuperClaudeService>(pub Arc<T>);
                    impl<
                        T: SuperClaudeService,
                    > tonic::server::UnaryService<super::GetConfigurationRequest>
                    for GetConfigurationSvc<T> {
                        type Response = super::GetConfigurationResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetConfigurationRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SuperClaudeService>::get_configuration(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetConfigurationSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/superclaude.v1.SuperClaudeService/UpdateConfiguration" => {
                    #[allow(non_camel_case_types)]
                    struct UpdateConfigurationSvc<T: SuperClaudeService>(pub Arc<T>);
                    impl<
                        T: SuperClaudeService,
                    > tonic::server::UnaryService<super::UpdateConfigurationRequest>
                    for UpdateConfigurationSvc<T> {
                        type Response = super::UpdateConfigurationResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UpdateConfigurationRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SuperClaudeService>::update_configuration(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UpdateConfigurationSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/superclaude.v1.SuperClaudeService/ListObsidianNotes" => {
                    #[allow(non_camel_case_types)]
                    struct ListObsidianNotesSvc<T: SuperClaudeService>(pub Arc<T>);
                    impl<
                        T: SuperClaudeService,
                    > tonic::server::UnaryService<super::ListObsidianNotesRequest>
                    for ListObsidianNotesSvc<T> {
                        type Response = super::ListObsidianNotesResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListObsidianNotesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SuperClaudeService>::list_obsidian_notes(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListObsidianNotesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/superclaude.v1.SuperClaudeService/GetObsidianNote" => {
                    #[allow(non_camel_case_types)]
                    struct GetObsidianNoteSvc<T: SuperClaudeService>(pub Arc<T>);
                    impl<
                        T: SuperClaudeService,
                    > tonic::server::UnaryService<super::GetObsidianNoteRequest>
                    for GetObsidianNoteSvc<T> {
                        type Response = super::GetObsidianNoteResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetObsidianNoteRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SuperClaudeService>::get_obsidian_note(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetObsidianNoteSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/superclaude.v1.SuperClaudeService/Ping" => {
                    #[allow(non_camel_case_types)]
                    struct PingSvc<T: SuperClaudeService>(pub Arc<T>);
                    impl<
                        T: SuperClaudeService,
                    > tonic::server::UnaryService<super::PingRequest> for PingSvc<T> {
                        type Response = super::PingResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PingRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SuperClaudeService>::ping(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = PingSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for SuperClaudeServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "superclaude.v1.SuperClaudeService";
    impl<T> tonic::server::NamedService for SuperClaudeServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
