"""Tests for .github/scripts/generate-architecture.sh.

Validates shell script syntax, security hardening, structural correctness,
and functional behavior via subprocess execution with mock binaries.
"""

import os
import subprocess
import textwrap
from pathlib import Path

import pytest

SCRIPT_PATH = (
    Path(__file__).parent.parent.parent / ".github" / "scripts" / "generate-architecture.sh"
)


# ── Tier 1: Static Analysis ──────────────────────────────────────────


class TestShellSyntax:
    """Validate shell script parses without errors."""

    def test_bash_syntax_check(self):
        """Script passes bash -n syntax validation."""
        result = subprocess.run(
            ["bash", "-n", str(SCRIPT_PATH)],
            capture_output=True,
            text=True,
        )
        assert result.returncode == 0, f"Syntax error: {result.stderr}"

    def test_shebang_present(self):
        """Script has a bash shebang line."""
        first_line = SCRIPT_PATH.read_text().split("\n")[0]
        assert first_line.startswith("#!/"), f"Missing shebang: {first_line}"
        assert "bash" in first_line


class TestErrorHandling:
    """Validate robust error handling settings."""

    def test_uses_strict_error_mode(self):
        """Script uses set -euo pipefail for robust error handling."""
        content = SCRIPT_PATH.read_text()
        assert "set -euo pipefail" in content


class TestDependencyValidation:
    """Validate that required tools are checked before use."""

    def test_check_deps_function_exists(self):
        """Script defines a check_deps function."""
        content = SCRIPT_PATH.read_text()
        assert "check_deps" in content

    def test_checks_for_required_tools(self):
        """check_deps validates jq and npx."""
        content = SCRIPT_PATH.read_text()
        for tool in ["jq", "npx"]:
            assert tool in content, f"Missing dependency check for {tool}"


class TestErrorReporting:
    """Validate that GitNexus errors are logged, not silently swallowed."""

    def test_no_bare_fallback_without_warning(self):
        """GitNexus query failures should log a warning before falling back."""
        content = SCRIPT_PATH.read_text()
        assert "::warning::" in content, (
            "Expected ::warning:: annotations for GitNexus query failures"
        )

    def test_cypher_errors_produce_empty_fallback(self):
        """Cypher query failures should return empty string fallback."""
        content = SCRIPT_PATH.read_text()
        assert 'echo ""' in content, "Expected empty string fallback for failed cypher queries"


class TestOutputValidation:
    """Validate that generated ARCHITECTURE.md is validated before output."""

    def test_validates_minimum_line_count(self):
        """Script checks that output has a minimum line count."""
        content = SCRIPT_PATH.read_text()
        assert "LINE_COUNT" in content
        assert "-lt 100" in content

    def test_validates_heading(self):
        """Script checks that output starts with a heading."""
        content = SCRIPT_PATH.read_text()
        assert "'^# '" in content or "heading" in content.lower()

    def test_validates_expected_sections(self):
        """Script checks for expected sections like 'Codebase Overview'."""
        content = SCRIPT_PATH.read_text()
        assert "Codebase Overview" in content
        assert "Architecture Diagram" in content
        assert "Functional Areas" in content
        assert "Key Execution Flows" in content
        assert "Testing Architecture" in content


class TestStructure:
    """Validate expected functions and structure."""

    EXPECTED_FUNCTIONS = [
        "check_deps",
        "resolve_repo",
        "cypher_query",
        "format_number",
        "replace_marker_content",
    ]

    def test_all_functions_defined(self):
        """Script defines all expected helper functions."""
        content = SCRIPT_PATH.read_text()
        for func in self.EXPECTED_FUNCTIONS:
            assert f"{func}()" in content or f"{func} ()" in content, f"Missing function: {func}()"


# ── Tier 2: Execution Tests ──────────────────────────────────────────


SEED_ARCHITECTURE = textwrap.dedent("""\
# SuperClaude Architecture

> Auto-generated by GitNexus knowledge graph analysis.
> Last updated: 2026-01-01 00:00 UTC

## Codebase Overview

<!-- auto:overview -->
| Metric | Count |
|--------|-------|
| Total symbols | 0 |
| Relationships | 0 |
| Execution flows | 0 |
| Python files | 0 |
| Rust files | 0 |
| GitHub workflows | 0 |
| Documentation files | 0 |
<!-- /auto:overview -->

SuperClaude is a test project.

## Architecture Diagram

```mermaid
graph TB
    subgraph CLI["CLI Layer"]
        Install["install"]
        Update["update"]
        Uninstall["uninstall"]
    end

    subgraph Core["Core Engine"]
        LoopOrch["Loop Orchestrator"]
        QualityAssess["Quality Assessment"]
    end

    subgraph AgentSystem["Agent System"]
        AgentReg["Agent Registry"]
        AgentSel["Agent Selector"]
    end

    subgraph MCPLayer["MCP Integration"]
        PAL["PAL MCP"]
        Rube["Rube MCP"]
    end

    subgraph SetupCore["Setup & Components"]
        Registry["Component Registry"]
        Installer["Component Installer"]
        Validator["System Validator"]
    end

    Install --> Registry
    Install --> Installer
    Update --> Registry
    LoopOrch --> QualityAssess
    AgentSel --> AgentReg

    style CLI fill:#4a9eff,color:#fff
    style Core fill:#ff6b6b,color:#fff
    style AgentSystem fill:#ffd93d,color:#333
    style MCPLayer fill:#6bcb77,color:#fff
    style SetupCore fill:#8b5cf6,color:#fff
```

## Functional Areas

### Core Engine (`core/`)
The central orchestration layer. Test area.

| Module | Purpose |
|--------|---------|
| `loop_orchestrator.py` | Agentic loop runner |
| `quality_assessment.py` | Multi-dimensional scoring |
| `metrics.py` | Telemetry collection |

### Agent System (`agents/`)
Agent discovery and selection.

| Component | Purpose |
|-----------|---------|
| `registry.py` | Agent indexing |
| `selector.py` | Intent matching |

### Setup & Installer (`setup/`)
CLI toolkit for components.

| Subsystem | Purpose |
|-----------|---------|
| CLI Commands | install, update, uninstall |
| Component Registry | Discovery and instantiation |
| System Validator | Requirement checks |

## Key Execution Flows

### 1. System Validation (7 steps)
Test flow description.

```
get_system_info -> check_node -> validate -> ValidationError
```

### 2. Component Installation (6 steps)
Installs a component.

```
install_component -> install -> validate_prerequisites
```

### 3. Component Update (6 steps)
Updates components.

```
perform_update -> create_component_instances -> get_metadata
```

## Testing Architecture

Tests mirror the source structure:

| Directory | Coverage |
|-----------|----------|
| `tests/core/` | Loop orchestrator, quality |
| `tests/agents/` | Registry, selector |
| `tests/setup/` | Uninstall, environment |
| `tests/integration/` | Workflow configs |
| `tests/e2e/` | Full pipeline |

---
*Generated by [GitNexus](https://github.com/nicholasgriffintn/gitnexus) code intelligence*
""")


@pytest.fixture
def mock_bin_dir(tmp_path):
    """Create a temp directory with mock binaries for npx and jq."""
    bin_dir = tmp_path / "bin"
    bin_dir.mkdir()

    # Mock npx: handles gitnexus list and cypher commands
    npx_script = bin_dir / "npx"
    npx_script.write_text(
        textwrap.dedent("""\
        #!/usr/bin/env bash
        if [[ "$1" == "gitnexus" && "$2" == "list" ]]; then
            echo "  Indexed Repositories (1)"
            echo ""
            echo "  TestRepo"
            echo "    Path: /tmp/test"
        elif [[ "$1" == "gitnexus" && "$2" == "cypher" ]]; then
            # Return mock count for any cypher query
            echo '{"markdown":"| c |\\n| --- |\\n| 42 |","row_count":1}'
        elif [[ "$1" == "gitnexus" && "$2" == "analyze" ]]; then
            echo "Indexed."
        else
            echo "mock npx: $*" >&2
        fi
    """)
    )
    npx_script.chmod(0o755)

    # Mock find: return fixed counts
    find_script = bin_dir / "find"
    find_script.write_text(
        textwrap.dedent("""\
        #!/usr/bin/env bash
        # Return a few lines so wc -l counts them
        echo "file1"
        echo "file2"
        echo "file3"
    """)
    )
    find_script.chmod(0o755)

    return bin_dir


@pytest.fixture
def run_generate(mock_bin_dir, tmp_path):
    """Helper to run generate-architecture.sh with mock environment."""

    def _run(extra_env=None, seed_content=SEED_ARCHITECTURE):
        work_dir = tmp_path / "repo"
        work_dir.mkdir(exist_ok=True)

        # Seed ARCHITECTURE.md with markers (required for marker-based updates)
        arch_file = work_dir / "ARCHITECTURE.md"
        arch_file.write_text(seed_content)

        # Create .github/workflows dir for find to count
        wf_dir = work_dir / ".github" / "workflows"
        wf_dir.mkdir(parents=True, exist_ok=True)

        env = os.environ.copy()
        env["PATH"] = f"{mock_bin_dir}:{env['PATH']}"
        env["HOME"] = str(tmp_path)

        if extra_env:
            env.update(extra_env)

        result = subprocess.run(
            ["bash", str(SCRIPT_PATH)],
            capture_output=True,
            text=True,
            env=env,
            cwd=str(work_dir),
            timeout=30,
        )
        arch_content = arch_file.read_text() if arch_file.exists() else ""
        return result, arch_content

    return _run


class TestExecution:
    """Functional tests via subprocess with mock binaries."""

    def test_updates_architecture_md(self, run_generate):
        """Script updates ARCHITECTURE.md preserving curated content."""
        result, content = run_generate()
        assert result.returncode == 0, f"Script failed: {result.stderr}"
        assert content.startswith("# SuperClaude Architecture")
        assert "## Codebase Overview" in content
        assert "## Architecture Diagram" in content
        assert "## Functional Areas" in content
        assert "## Key Execution Flows" in content
        assert "## Testing Architecture" in content

    def test_updates_file_counts(self, run_generate):
        """Updated file includes file count table with data from cypher queries."""
        result, content = run_generate()
        assert result.returncode == 0
        assert "Python files" in content
        assert "Rust files" in content
        assert "Total symbols" in content
        assert "Relationships" in content

    def test_preserves_curated_content(self, run_generate):
        """Script preserves hand-curated content outside markers."""
        result, content = run_generate()
        assert result.returncode == 0
        # These sections are from the seed and should be preserved
        assert "SuperClaude is a test project" in content
        assert "graph TB" in content  # Mermaid diagram
        assert "Test area" in content  # Functional area description
        assert "Test flow description" in content  # Execution flow

    def test_includes_footer(self, run_generate):
        """Updated file preserves GitNexus attribution footer."""
        result, content = run_generate()
        assert result.returncode == 0
        assert "GitNexus" in content
        assert "code intelligence" in content

    def test_updates_timestamp(self, run_generate):
        """Script updates the last-updated timestamp."""
        result, content = run_generate()
        assert result.returncode == 0
        assert "2026-01-01 00:00 UTC" not in content  # Old timestamp replaced
        assert "Last updated:" in content

    def test_fails_without_architecture_md(self, mock_bin_dir, tmp_path):
        """Script fails with error if ARCHITECTURE.md is missing."""
        work_dir = tmp_path / "empty_repo"
        work_dir.mkdir()

        env = os.environ.copy()
        env["PATH"] = f"{mock_bin_dir}:{env['PATH']}"
        env["HOME"] = str(tmp_path)

        result = subprocess.run(
            ["bash", str(SCRIPT_PATH)],
            capture_output=True,
            text=True,
            env=env,
            cwd=str(work_dir),
            timeout=30,
        )
        assert result.returncode != 0
        assert "not found" in result.stderr

    def test_fails_without_markers(self, mock_bin_dir, tmp_path):
        """Script fails with error if ARCHITECTURE.md has no markers."""
        work_dir = tmp_path / "no_markers"
        work_dir.mkdir()
        (work_dir / "ARCHITECTURE.md").write_text("# Architecture\n\nNo markers here.\n")

        env = os.environ.copy()
        env["PATH"] = f"{mock_bin_dir}:{env['PATH']}"
        env["HOME"] = str(tmp_path)

        result = subprocess.run(
            ["bash", str(SCRIPT_PATH)],
            capture_output=True,
            text=True,
            env=env,
            cwd=str(work_dir),
            timeout=30,
        )
        assert result.returncode != 0
        assert "marker" in result.stderr.lower()

    def test_missing_dependency_exits_with_error(self, tmp_path):
        """Missing jq causes exit 1 with error message."""
        # Create a restricted PATH with symlinks to real coreutils but NOT jq.
        bin_dir = tmp_path / "restricted_bin"
        bin_dir.mkdir()
        # Symlink real binaries we need (not jq)
        import shutil

        for cmd in [
            "cat",
            "wc",
            "sort",
            "date",
            "head",
            "grep",
            "find",
            "sed",
            "tr",
            "printf",
            "dirname",
            "basename",
            "mkdir",
            "chmod",
            "rm",
            "echo",
            "test",
            "command",
            "awk",
            "mv",
        ]:
            real = shutil.which(cmd)
            if real:
                os.symlink(real, bin_dir / cmd)
        # Mock npx (no real npx needed)
        npx_mock = bin_dir / "npx"
        npx_mock.write_text("#!/bin/bash\necho mock")
        npx_mock.chmod(0o755)

        env = {"PATH": str(bin_dir), "HOME": str(tmp_path)}
        result = subprocess.run(
            ["/usr/bin/bash", str(SCRIPT_PATH)],
            capture_output=True,
            text=True,
            env=env,
            cwd=str(tmp_path),
            timeout=10,
        )
        assert result.returncode != 0
        assert "jq" in result.stderr
