#!/usr/bin/env python3
"""
GitHub Commit Suggestion Generation (Phase 1)

Generates suggestion-only PRs with GitHub's commit suggestion syntax.
No direct code changes - all improvements require manual review and approval.
"""

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict

CATEGORY_EMOJI = {
    "security": "🔒",
    "quality": "✨",
    "performance": "⚡",
    "tests": "🧪",
}

CATEGORY_DESCRIPTION = {
    "security": "Security vulnerabilities and hardening opportunities",
    "quality": "Code quality, maintainability, and SOLID principle adherence",
    "performance": "Performance optimizations and efficiency improvements",
    "tests": "Test coverage gaps and test quality improvements",
}

SEVERITY_EMOJI = {
    "critical": "🔴",
    "high": "🟠",
    "medium": "🟡",
    "low": "🔵",
}


def load_fix_plan(fix_plan_file: Path) -> Dict[str, Any]:
    """Load fix plan JSON."""
    try:
        with open(fix_plan_file, "r") as f:
            return json.load(f)
    except (OSError, json.JSONDecodeError) as e:
        print(f"Error loading fix plan {fix_plan_file}: {e}", file=sys.stderr)
        return None


def generate_finding_suggestion_block(finding: Dict[str, Any]) -> str:
    """Generate suggestion block for a single finding."""
    severity = finding.get("severity", "medium")
    file_path = finding.get("file", "unknown")
    line_start = finding.get("line_start", 1)
    issue = finding.get("issue", "No description")
    suggestion = finding.get("suggestion", "No suggestion")
    confidence = finding.get("confidence", 0)

    # Format suggestion block
    block = f"""
### {SEVERITY_EMOJI[severity]} {severity.upper()}: {issue}

**File**: `{file_path}:{line_start}`
**Confidence**: {confidence:.0%}

**Issue**: {issue}

**Suggested Fix**:
{suggestion}

---
"""
    return block


def generate_pr_description(category: str, fix_plan: Dict[str, Any]) -> str:
    """Generate PR description for a category (Phase 2: skip autofix-eligible)."""
    all_findings = fix_plan.get("findings", [])

    # Phase 2: Filter out autofix-eligible findings (they go in separate PR)
    findings = [f for f in all_findings if not f.get("autofix_eligible", False)]

    if not findings:
        # All findings are autofix-eligible, no suggestion-only PR needed
        return None

    severity_counts = fix_plan.get("severity_counts", {})
    summary_info = fix_plan.get("summary", {})

    emoji = CATEGORY_EMOJI.get(category, "📋")
    description = CATEGORY_DESCRIPTION.get(category, "Code improvements")

    # Header
    pr_desc = f"""# {emoji} Nightly Code Review: {category.upper()}

{description}

## Summary

- **Total Findings**: {fix_plan.get("total_findings", 0)}
- **Files Affected**: {summary_info.get("files_affected", 0)}
- **Average Confidence**: {summary_info.get("avg_confidence", 0):.0%}

### Findings by Severity

| Severity | Count |
|----------|-------|
| {SEVERITY_EMOJI["critical"]} Critical | {severity_counts.get("critical", 0)} |
| {SEVERITY_EMOJI["high"]} High | {severity_counts.get("high", 0)} |
| {SEVERITY_EMOJI["medium"]} Medium | {severity_counts.get("medium", 0)} |
| {SEVERITY_EMOJI["low"]} Low | {severity_counts.get("low", 0)} |

---

## Detailed Findings

"""

    # Add each finding
    for idx, finding in enumerate(findings, start=1):
        pr_desc += f"## Finding #{idx}\n"
        pr_desc += generate_finding_suggestion_block(finding)

    # Footer
    autofix_note = ""
    autofix_count = summary_info.get("autofix_eligible", 0)
    if autofix_count > 0:
        autofix_note = f"""
### ⚡ Autofix Available

**{autofix_count} findings** from this category are eligible for automatic fixes and will appear in a separate autofix PR with actual code changes. This PR contains only the remaining suggestion-only findings.

"""

    pr_desc += f"""
---

## How to Use This PR

This PR contains **suggestions only** - no code has been automatically modified.

{autofix_note}### Applying Suggestions

1. Review each finding above
2. For suggestions you agree with, click "Commit suggestion" in the PR diff view
3. GitHub will create a commit with your approval

### Manual Implementation

For complex suggestions requiring architectural changes:
1. Use the suggestion as a guide
2. Implement the fix manually in your local branch
3. Test thoroughly before committing

---

**Generated by**: SuperClaude Nightly Code Review
**Review Method**: PAL MCP Multi-Model Consensus
**Review Date**: {fix_plan.get("timestamp", "N/A")}
**Phase**: Phase 2 (Suggestion-only + Limited Autofix)

**Note**: This is a proactive, advisory review. All changes require human approval.
"""

    return pr_desc


def main():
    parser = argparse.ArgumentParser(
        description="Generate GitHub commit suggestions from fix plans"
    )
    parser.add_argument(
        "--fix-plans-dir", type=Path, required=True, help="Directory containing fix plan JSON files"
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("pr-content"),
        help="Output directory for PR content",
    )

    args = parser.parse_args()

    if not args.fix_plans_dir.exists():
        print(f"Error: Fix plans directory not found: {args.fix_plans_dir}", file=sys.stderr)
        sys.exit(1)

    # Create output directory
    args.output_dir.mkdir(parents=True, exist_ok=True)

    # Process each category
    categories = ["security", "quality", "performance", "tests"]
    prs_generated = 0

    for category in categories:
        fix_plan_file = args.fix_plans_dir / f"{category}.json"

        if not fix_plan_file.exists():
            print(f"No fix plan for {category} - skipping")
            continue

        fix_plan = load_fix_plan(fix_plan_file)
        if not fix_plan or not fix_plan.get("findings"):
            print(f"No findings in {category} fix plan - skipping")
            continue

        # Generate PR description
        pr_description = generate_pr_description(category, fix_plan)

        # Phase 2: Skip if all findings are autofix-eligible
        if pr_description is None:
            print(f"All {category} findings are autofix-eligible - skipping suggestion PR")
            continue

        # Write to output file
        output_file = args.output_dir / f"{category}-pr.md"
        with open(output_file, "w") as f:
            f.write(pr_description)

        print(f"Generated PR content for {category}: {output_file}")
        prs_generated += 1

    if prs_generated == 0:
        print("\nNo PR content generated (no findings)")
    else:
        print(f"\nGenerated {prs_generated} PR descriptions in {args.output_dir}")


if __name__ == "__main__":
    main()
