defaults:
  vote_type: majority
  quorum_size: 2
commands:
  implement:
    vote_type: quorum
    quorum_size: 3
  build:
    vote_type: majority
    quorum_size: 2
  test:
    vote_type: majority
    quorum_size: 2
