# SuperClaude Framework MCP Server Configuration
# Version: 6.0.0-alpha

servers:
  zen:
    enabled: true
    name: Multi-Model Orchestrator
    triggers:
      - --zen
      - --consensus
      - --thinkdeep
      - --zen-review
    capabilities:
      - multi-model-consensus
      - deep-thinking
      - code-review
      - validation
    priority: high

  deepwiki:
    enabled: true
    name: Documentation Repository
    triggers:
      - --deepwiki
      - --docs
      - /docs
      - --library-docs
    capabilities:
      - documentation-fetch
      - library-reference
      - framework-patterns
      - code-examples
      - api-reference
    priority: medium

  rube:
    enabled: true
    name: Rube Automation Hub
    triggers:
      - --rube
      - --external
    capabilities:
      - automation-proxy
      - cross-app-integration
      - oauth-broker
    priority: low
    requires_network: true
    endpoint: https://rube.app/mcp
    timeout_seconds: 60

# Integration Configuration
integration:
  auto_enable:
    complexity_threshold: 0.7
    multi_domain: true
    performance_mode: false

  orchestration:
    concurrent_servers: 3
    timeout: 300
    retry_limit: 2

  coordination:
    zen_validation: true          # Zen validates critical operations

# Performance Configuration
performance:
  batch_operations: true
  parallel_execution: true
  cache_results: true
  stream_responses: true

  limits:
    max_concurrent: 5
    memory_limit: 2GB
    token_budget: 100000
