# SuperClaude Framework MCP Server Configuration
# Version: 6.0.0-alpha

servers:
  magic:
    enabled: true
    name: Magic UI Generator
    triggers:
      - /ui
      - /21
      - --magic
      - --tools magic
    capabilities:
      - ui-generation
      - component-creation
      - accessibility
      - responsive-design
    priority: high

  sequential:
    enabled: true
    name: Sequential Thinking
    triggers:
      - --think
      - --think-hard
      - --ultrathink
      - --seq
    capabilities:
      - multi-step-reasoning
      - hypothesis-testing
      - complex-analysis
      - debugging
    priority: high

  serena:
    enabled: true
    name: Project Memory & Symbols
    triggers:
      - --serena
      - /sc:load
      - /sc:save
    capabilities:
      - session-memory
      - symbol-operations
      - checkpointing
      - context-persistence
    priority: medium

  playwright:
    enabled: true
    name: Browser Automation
    triggers:
      - --play
      - --playwright
      - --e2e
    capabilities:
      - browser-testing
      - e2e-testing
      - accessibility-testing
      - visual-validation
    priority: medium

  zen:
    enabled: true
    name: Multi-Model Orchestrator
    triggers:
      - --zen
      - --consensus
      - --thinkdeep
      - --zen-review
    capabilities:
      - multi-model-consensus
      - deep-thinking
      - code-review
      - validation
    priority: high

  deepwiki:
    enabled: true
    name: Documentation Repository
    triggers:
      - --deepwiki
      - --docs
      - /docs
      - --library-docs
    capabilities:
      - documentation-fetch
      - library-reference
      - framework-patterns
      - code-examples
      - api-reference
    priority: medium

# Integration Configuration
integration:
  auto_enable:
    complexity_threshold: 0.7
    multi_domain: true
    performance_mode: false

  orchestration:
    concurrent_servers: 3
    timeout: 300
    retry_limit: 2

  coordination:
    sequential_then_magic: true  # Sequential analyzes, Magic implements
    serena_persistence: true      # Auto-checkpoint with Serena
    zen_validation: true          # Zen validates critical operations

# Performance Configuration
performance:
  batch_operations: true
  parallel_execution: true
  cache_results: true
  stream_responses: true

  limits:
    max_concurrent: 5
    memory_limit: 2GB
    token_budget: 100000